### PR TITLE
Support File for PropertyType in  #240

### PR DESCRIPTION
**Pull request by cecol**
For #240, if any problem or bug, please tell me.

### CODE REVIEW

**Comment by afsalthaj** [comment]
Hey could you do sbt fmt and push again ?

**Comment by cecol** [comment]
Sorry, I forget to adjust my Intellij IDEA format preference. I fix it and pass `sbt check` on my local PC.

**Comment by jdegoes** [comment]
@cecol Can you just fix conflicts and then @afsalthaj can merge?

**Comment by afsalthaj** [comment]
@cecol should we actually check for existence for File ? I guess we can avoid that step?

**Comment by cecol** [comment]
@afsalthaj My original code didn't check the existence of the File, but that would get another problem of PropertyTypeTest. I have no idea how to program the invalid test case. since the `new File(_)`  accepts any arbitrary String without exceptions.

**Pull request merged**
