### PR TITLE
remove cross version modifier for scala-collection-compat

### PR DESCRIPTION
**Pull request by sviezypan**
This is causing problems when you try to use zio-config in scala 3 application together with some other library which uses scala-collection-compat_3 (for example zio-http)

### CODE REVIEW

**Review by afsalthaj — APPROVED** [review]

**Comment by afsalthaj** [comment]
@sviezypan  Could u run a `sbt fmt` fixing the format errors?

**Comment by sviezypan** [comment]
@afsalthaj what is required for ci status to be reported? can it be triggered?

**Review by afsalthaj — APPROVED** [review]

**Comment by afsalthaj** [comment]
Appreciate your patience that you had to merge with master couple of times.
The master branch is attacked by rest of the Scala-steward, and I had to merge a few scala3 changes by myself..

**Comment by sviezypan** [comment]
thank you @afsalthaj, looks like ti can be merged. Is there a plan for realease anytime soon?

**Comment by afsalthaj** [comment]
Possibly tomorrow 2pm AEST.

**Comment by afsalthaj** [comment]
Thanks heaps for your contribution.

**Pull request merged**
