### PR TITLE
Removed silencer SBT plugin

### PR DESCRIPTION
**Pull request by tPl0ch**
The plugin is not necessary anymore since it was back-ported to all currently supported compiler versions. It also breaks when using this library with the 3.3.1-RC1 Scala version:

```
[error] -- Error: typesafe/shared/src/main/scala/zio/config/typesafe/TypesafeConfigSource.scala:15:0
[error] undefined: new com.github.ghik.silencer.silent # -1: TermRef(TypeRef(TermRef(ThisType(TypeRef(NoPrefix,module class ghik)),object silencer),silent),<init>) at readTasty
```

I also added a few improvements in the build itself, and fixed a few tests.

### CODE REVIEW

**Comment by tPl0ch** [comment]
@afsalthaj I guess this touches a lot of points of https://github.com/zio/zio-config/pull/1091

Will you be able to merge #1091 at some point? Then I'd rebase this branch against master again.

**Comment by afsalthaj** [comment]
@tPl0ch  Yes, Il try to merge #1091 . This looks good, thanks

**Comment by olafmaurer** [comment]
Will a fix for this also be merged into a new zio-config 3 release? It would be nice to be able to use it with Scala 3.3.

**Comment by seakayone** [comment]
Nice.
For those who are interested: I found a workaround. 
In order to use zio-config with scala 3.3.0 I added the silencer lib from scala 2.13 to the dependencies:
`"com.github.ghik"       % "silencer-lib_2.13.11"     % "1.7.13"`
this way `sbt doc` would pass.

**Comment by afsalthaj** [comment]
Apologies for the big delay here, as I completely missed out to follow up.

**Comment by khajavi** [comment]
> @afsalthaj I guess this touches a lot of points of #1091
> 
> Will you be able to merge #1091 at some point? Then I'd rebase this branch against master again.

Can you help me on updating #1091 with the latest changes?

**Comment by khajavi** [comment]
@tPl0ch I Forgot to ping you, on the previous comment. Need your help, if you have free time!

**Pull request merged**
