### PR TITLE
Fix website 2

### PR DESCRIPTION
**Pull request by sideeffffect**
/cc @mijicd

### CODE REVIEW

**Comment by sideeffffect** [comment]
@mijicd When we test in CI only `docs/mdoc`, but not `docs/docusaurusCreateSite`, we do not prevent failures in master when trying to deploy the website :crying_cat_face:

**Review by mijicd — DISMISSED** [review]

**Comment by sideeffffect** [comment]
green :tada:

**Review by mijicd — APPROVED** [review]

**Comment by sideeffffect** [comment]
We're getting this. Any idea how to fix that?
```
ERROR: Permission to zio/zio-config.git denied to deploy key
```
https://github.com/zio/zio-config/runs/2565386218?check_suite_focus=true#step:4:372

**Comment by mijicd** [comment]
@softinio is the keeper of the keys, so he's the only one that can help here :)

**Pull request merged**
