### PR TITLE
Add support for more data types

### PR DESCRIPTION
**Pull request by marekklis**
Does support for UUID require something else?

### CODE REVIEW

**Comment by marekklis** [comment]
I have no idea why github shows that whole `PropertyTypeTest.scala` file was changed. I used `sbt scalafmtAll` to format code before commiting

**Comment by afsalthaj** [comment]
This is great. If it won't take much of your time, do you mind adding more supporting other types mentioned in the same issue #240

**Comment by marekklis** [comment]
I'll add support for other types

**Comment by afsalthaj** [comment]
@marekklis  Excellent!

**Comment by marekklis** [comment]
I've added support for `LocalDate`, `LocalTime`, `LocalDateTime`, `Instant` types

**Comment by afsalthaj** [comment]
If that fixes all of the types mentioned, then I think we can close #240 and merge this one

**Comment by afsalthaj** [comment]
I think everyone is staying home and pushing!
Build is taking time :)

**Pull request merged**
