### PR TITLE
Add support for Set data types

### PR DESCRIPTION
**Pull request by marekklis**
For https://github.com/zio/zio-config/issues/240

### CODE REVIEW

**Comment by jdegoes** [comment]
@marekklis I would instead implement this atop `List`, and convert to `Set` using the mapping functions.

**Comment by afsalthaj** [comment]
@marekklis  Let me know if you have any questions.
Its recursively applying to finally obtain the set, and the initial node is `list`.
list(config).map(l => ...)

and will be part of `ConfigDescriptor` companion object

**Comment by marekklis** [comment]
Reimplemented using `list` `ConfigDescriptor`

**Comment by jdegoes** [comment]
@marekklis Looks great! Can you merge in the latest changes into your code, so we can merge in this pull request?

**Comment by marekklis** [comment]
@jdegoes Latest changes were merged into my code

**Comment by afsalthaj** [comment]
@marekklis  Missed out merging your code. I have updated the branch with the master.

**Comment by senia-psm** [comment]
@marekklis Sorry, I was going to suggest changes, not to add another commit. Hope you don't mind.

**Pull request merged**
