### PR TITLE
WIP: PropertyTree Optimizations

### LINKED ISSUE #418: Very slow performance with large number of env vars.
When you run your app on Kubernetes there are a lot of env vars defined. At least two for each service. So in my case there are 800 of env vars like `LONG_SERVICE_NAME_HOST` and `ANOTHER_LONG_SERVICE_NAME_PORT`. 

And it seems that config loading is stuck forever in `PropertyTree#mergeAll`.

### PR DESCRIPTION
**Pull request by tusharmath**
Should Fix #418

### CODE REVIEW

**Comment by afsalthaj** [comment]
This PR is promising @tusharmath.
Thanks for introducing thoughts on asymptotic analysis into PropertyTree. 
Looking forward

**Comment by tusharmath** [comment]
**Some initial thoughts**

1. Consider a property tree of 10 keys being merged with another of 10 keys. The total number of options produced will be equal to `2^10 = 1024`. 
2. Clearly the memory requirement also increases exponentially and using a mutable data structure might not really help.
3. I think a more lazy solution might actually perform better.
4. Alternatively we can create a new API to merge two tree with a conflict resolver, such that instead of returning a list it returns a single merge property tree.

_Please correct me if I am wrong_

**Comment by afsalthaj** [comment]
Merging trees should produce multiple possibilities returning a list. Changing that can cause issues in future.

A laziness approach would be rather better but we need to see how that goes. I was pretty busy with a few other changes, but happy to work with you on this.

Meanwhile, as a first step (or as a minimum requirement) we need a filter function that allows us to fetch a trimmed down version of the tree especially for sources such as system-env, properties etc. `convertKeys` & `mapKeys` are playing on an already-fetched tree, and hence this change need to be within each source. This is related to https://github.com/zio/zio-config/issues/471

**Comment by afsalthaj** [comment]
Also, probably merging trees should produce only distinct trees. I think we should ensure that as well as the next stage improvement

**Comment by afsalthaj** [comment]
Hi @tusharmath 
How are we going about this issue ? (While I know you have been super busy with some wonderful contributions in zio space)

**Comment by tusharmath** [comment]
Haven't been able to spend much time on this. Apologies for that. Please
feel free to assign it to yourself.

**Comment by afsalthaj** [comment]
@tusharmath No worries.

**Pull request closed without merging**
